spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 300KB
      max-request-size: 300KB
      #todo: what if we want to update sth else like a video instead of an image!?

