spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      #todo: what if we want to update sth else like a video instead of an image!?

  mail:
    host: smtp.gmail.com
    port: 587
    username: irezashn@gmail.com
    password: PutPasswordHere
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true



